import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CardComponent from "../src/components/CardComponent";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Country Quiz</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <div className={styles.mainContainer}>
                    <h1 className={styles.title}>
                        Country Quiz
                    </h1>
                    <CardComponent></CardComponent>
                </div>

            </main>

            <footer className={styles.footer}>
                created by <a href="https://github.com/celestedubini">celestedubini</a>- devChallenges.io
            </footer>
        </div>
    )
}

export default Home
